# Generated by Django 3.0.5 on 2023-01-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0012_auto_20230123_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='carrier_reference_no',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='reciever_address',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='reciever_email',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='reciever_name',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='reciever_phone',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='sender_phone',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='service',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='status',
        ),
        migrations.AddField(
            model_name='courier',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
