# Generated by Django 4.1.6 on 2023-02-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0018_auto_20230207_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='payment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
