# Generated by Django 3.0.5 on 2023-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0019_courier_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('departure', models.CharField(max_length=200, null=True)),
                ('arrival', models.CharField(max_length=500, null=True)),
                ('cargo_description', models.CharField(max_length=1000, null=True)),
                ('transportation_method', models.CharField(max_length=500, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
