# Generated by Django 3.0.5 on 2023-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0020_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='cargo_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
