# Generated by Django 3.0.5 on 2023-04-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0021_auto_20230424_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
