# Generated by Django 3.0.5 on 2023-04-28 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0022_auto_20230428_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='couriermanage.Courier'),
        ),
    ]
