# Generated by Django 3.0.5 on 2023-04-29 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0023_auto_20230428_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingHistroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255, null=True)),
                ('current_status', models.CharField(max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='departure_time',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='expected_delivery_date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='payment',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='content',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='reciever_address',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='reciever_phone',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='sender_address',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='shippinghistroy',
            name='parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='couriermanage.Courier'),
        ),
    ]
